### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by brechtdecock** [KiseKloset/KiseKloset#8]
1) does it work on windows
2) how should the .env file be configured? the example does not make clear what i should do in my case
3) the KiseKloset link (opening http://selab.edu.vn:20440/) does not work

**Comment by zero-nnkn** [comment]
1. We just developed and tested this code on Linux. It may not work well on Windows. You may need to modify the code (ensure you have a GPU).
2. You just need to care about the `HOST` and `PORT`. They will determine your website address (in local). More details: [FastAPI deployment](https://fastapi.tiangolo.com/deployment/manually/).
3. We have stopped hosting at http://selab.edu.vn:20440/.
Hope it's useful.
